{
 "title": "Playground",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Types",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group(columns: [\"type\"])\r\n  |> count()\r\n  |> group()\r\n  |> keep(columns: [\"_value\", \"type\"])"
    }
   ]
  },
  {
   "title": "Sources",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group(columns: [\"src\"])\r\n  |> count()\r\n  |> group()\r\n  |> keep(columns: [\"_value\", \"src\"])"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group(columns: [\"response_code\"])\r\n  |> count()\r\n  |> group()\r\n  |> keep(columns: [\"_value\", \"response_code\"])"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group(columns: [\"query\"])\r\n  |> count()\r\n  |> group()\r\n  |> keep(columns: [\"query\", \"_value\"])\r\n  |> sort(columns: [\"_value\"], desc:true)\r\n  |> rename(columns: {_value: \"Times\", query: \"Doamin\"})"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group()\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Blocked Queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\" and r[\"blocked\"] == \"true\")\r\n  |> group()\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Known Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Clients" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group()\r\n  |> unique(column: \"src\")\r\n  |> count()"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group()\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: 30s, fn: mean)\r\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "req/min" } },
   "targets": [
    {
     "query": "from(bucket: \"dns-hole\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"queries\")\r\n  |> group(columns: [\"src\"])\r\n  |> aggregateWindow(every: 1m, fn: count)\r\n  |> keep(columns: [\"_time\", \"src\", \"_value\"])"
    }
   ]
  }
 ]
}